#name: Configuration du projet
#on: push
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout du projet
#        uses: actions/checkout@v4
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: "17"
#          distribution: "temurin"
#
#      - name: Installation des dépendances
#        run: mvn install
#
#      - name: Cache Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Build de l'application
#        run: echo "Build de mon application..."
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: 'dist-files'
#          path: 'target/*.jar'